### ISSUE TITLE
Bring over newer content

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#35]
Since we migrated the content wholesale in July, some new things have been added. Here are the things we should manually bring over:

- [ ] Blog posts
- [x] People (including adding bio blurbs, latest titles for former Praxis students who later got other SLab fellowships/roles)
- [ ] Events
- [x] Research project
- [x] DH Fellowship and Grad Opportunities pages, which have been restructured

**Comment by amandavisconti** [comment]
Moved Spyros' 9/10 blog post, gonna tune into Praxis atm but will work on others. As of 9/12 (before Christian's blog post was published), 10 other posts to add to new site.

**Comment by amandavisconti** [comment]
Posts before Christian's 9/12 post but after the first website sprint have been moved in, except for the following:
http://scholarslab.org/wp-admin/post.php?post=13663&action=edit  
http://scholarslab.org/wp-admin/post.php?post=13650&action=edit  
http://scholarslab.org/wp-admin/post.php?post=13656&action=edit  
http://scholarslab.org/wp-admin/post.php?post=13643&action=edit  
http://scholarslab.org/wp-admin/post.php?post=13636&action=edit

**Comment by amandavisconti** [comment]
Asked on Slack: Where are we with moving content to the new site? Would it help for me to manually move stuff that’s new since the summer website sprint, or can we just do a new export of the WP site? (can’t remember if we updated YAML after moving things to the Jekyll site…)

**Comment by walshbr** [comment]
If we do decide to do a fresh export of the WP content, I have a heavily modified version of the export script that we'd probably want to use. I believe it's on my laptop currently in Charlottesville though.

**Comment by amandavisconti** [comment]
Moving my list of to-dos to a new comment for the January 2018 sprint:

As of 9/14 11am, need to migrate the following posts:
- [ ] /etc/rc.local  
- [ ] About my research, computers and Digital Humanities  (migrated but formatting bad)
- [x] Hello World!  
- [x] Digital Humanities Fellows Applications – 2018-2019  
- [x] 2017 Virginia Higher Ed GIS Meeting  
- [x] CFP: PMLA Special Issue, Varieties of Digital Humanities  
- [x] Welcome Senior Developer Shane Lin!  
- [x] Fall 2017 UVa Library GIS Workshop Series  
- [x] What can digital humanities tell us about Character?  
- [x] Transcribing Typography with Markdown  
- [ ] Anything posted after 9/14 11am  

Will need to go through and check for 
- [ ] Author appears at top of blog
- [ ] Pandoc doing weird line-wrapping on some of these
- [ ] Images appearing
- [ ] Image caption formatting
- [ ] Footnotes working
- [ ] Shortcodes
  
=========================

For content created after 9/14 11am, I need to move all:
- [ ] people (including adding bio blurbs, latest titles for former Praxis students who later got other SLab fellowships/roles)
- [ ] events
- [ ] static pages (e.g. DH Fellowship and Grad Opportunities pages, which have been restructured)
- [ ] recent blog post drafts

**Comment by walshbr** [comment]
Going to break some of these out into their own issues.

**Comment by walshbr** [comment]
#57 should cover the newer people data made since the summer.

**Comment by walshbr** [comment]
#60 takes care of the updates I've recently made to the grad fellowships programs.

**Comment by jeremyboggs** [comment]
> If we do decide to do a fresh export of the WP content, I have a heavily modified version of the export script that we'd probably want to use. I believe it's on my laptop currently in Charlottesville though.

@walshbr Where is this script? Can you share it? or, did you download it from somewhere?

**Comment by walshbr** [comment]
I downloaded it from this great guy named @jeremyboggs -https://github.com/jeremyboggs/exitwp. 😄 
Actually looks like I was committing as I went to your fork, and I just committed the last stuff that I had locally. So you should have the most up to date version there. But worth noting that this was modified based on the old data structure, so it's probably been rendered out of date by whatever changes we've made.

**Comment by jeremyboggs** [comment]
@walshbr Nah, think there are too many issues with the existing import, that I'd like to explore redoing it entirely.

**Comment by amandavisconti** [comment]
@jeremyboggs I could dedicate 1-2 days in May to going through your new export and adjusting metadata/broken links, if you let me know when you're ready to export? (I'd been planning on exporting and diff'ing against the stuff already on the old site that may have edits/new metadata, but maybe I should just focus on augmenting your new export?)

**Comment by amandavisconti** [comment]
@jeremyboggs if you let me know when you've re-migrated stuff, i can take a day and go through the rest of the issues to clean up content (for stuff the re-migration doesn't solve)

**Comment by amandavisconti** [comment]
[Label for issues we should wait on until after data re-migration](https://github.com/scholarslab/scholarslab.org/issues?q=is%3Aopen+is%3Aissue+label%3Await-for-content-remigration)

**Comment by amandavisconti** [comment]
Closing this, assigning myself #299 to do final sweep of new content/edits from WP site before public launch
